# Generated by Django 2.1.7 on 2019-03-02 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('art_title', models.CharField(max_length=128)),
                ('art_author', models.CharField(max_length=64)),
                ('art_content', models.TextField()),
                ('art_create_date', models.DateField(auto_now_add=True)),
                ('art_last_date', models.DateField(auto_now=True)),
                ('art_click_count', models.IntegerField()),
                ('art_lift', models.IntegerField()),
                ('art_comment', models.TextField()),
                ('art_image', models.ImageField(upload_to='', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('user_picurl', models.CharField(max_length=128, null=True)),
                ('user_name', models.CharField(max_length=32)),
                ('user_sex', models.CharField(choices=[(0, '男'), (1, '女')], max_length=8)),
                ('user_occupation', models.CharField(choices=[(0, '教师'), (1, '学生')], max_length=8)),
                ('user_Id', models.CharField(max_length=32)),
                ('user_passwd', models.CharField(max_length=32)),
                ('user_email', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='articleType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.ArticleType'),
        ),
    ]
