# Generated by Django 2.1.7 on 2019-03-03 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alltype',
            fields=[
                ('atid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='articletype',
            name='from_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.Alltype'),
        ),
    ]
