# Generated by Django 2.1.7 on 2019-03-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_auto_20190303_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='art_lift',
        ),
        migrations.AddField(
            model_name='article',
            name='art_lift',
            field=models.ManyToManyField(to='reception.UserInfo'),
        ),
    ]
