# Generated by Django 2.1.7 on 2019-03-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_auto_20190304_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='art_author_lift',
            field=models.ManyToManyField(to='reception.UserInfo'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='art_lift',
        ),
        migrations.AddField(
            model_name='article',
            name='art_lift',
            field=models.IntegerField(default=0),
        ),
    ]
