# Generated by Django 2.1.7 on 2019-02-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('user_picurl', models.CharField(max_length=128)),
                ('user_name', models.CharField(max_length=32)),
                ('user_sex', models.CharField(choices=[(0, '男'), (1, '女')], max_length=8)),
                ('user_occupation', models.CharField(choices=[(0, '教师'), (1, '学生')], max_length=8)),
                ('user_Id', models.CharField(max_length=32)),
                ('user_passwd', models.CharField(max_length=32)),
                ('user_email', models.CharField(max_length=64)),
            ],
        ),
    ]
