# Generated by Django 2.1.7 on 2019-02-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_email',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_picurl',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
